CREATE DATABASE bdPartidoPTC

USE bdPartidoPTC

SELECT * FROM Filiados_PTC

SELECT COUNT (numero_da_inscricao ) AS 'Número inscrição' FROM Filiados_PTC 

 SELECT NOME_DO_FILIADO FROM Filiados_PTC
 WHERE NOME_DO_FILIADO LIKE 'ANTONIO%'--1

 SELECT NOME_DO_FILIADO FROM Filiados_PTC
 WHERE NOME_DO_FILIADO LIKE '%SEBASTIAO'--2

 SELECT NOME_DO_FILIADO FROM Filiados_PTC
 WHERE NOME_DO_FILIADO LIKE 'OS%'--3

 SELECT NOME_DO_FILIADO FROM Filiados_PTC
 WHERE NOME_DO_MUNICIPIO LIKE '%LIX'--4

 SELECT NOME_DO_FILIADO FROM Filiados_PTC
 WHERE NOME_DO_MUNICIPIO LIKE 'INHAMBUPE'--5

 SELECT NOME_DO_MUNICIPIO FROM Filiados_PTC
 WHERE NOME_DO_MUNICIPIO LIKE 'SANTA%' --6

 SELECT NOME_DO_MUNICIPIO FROM Filiados_PTC
 WHERE NOME_DO_MUNICIPIO LIKE 'E%'--7

 SELECT NOME_DO_MUNICIPIO FROM Filiados_PTC
 WHERE NOME_DO_MUNICIPIO LIKE '%CRUZ%'--8

 SELECT NOME_DO_MUNICIPIO FROM Filiados_PTC
 WHERE NOME_DO_MUNICIPIO LIKE '%DE%'--9

 SELECT NOME_DO_FILIADO AS 'Nome do Filiado', DATA_DA_FILIACAO AS 'Data da Filiação' FROM Filiados_PTC
 WHERE DATA_DA_FILIACAO BETWEEN '01-01-1990' AND '01-01-2000'--10


 SELECT NOME_DO_FILIADO AS 'Nome do Filiado', DATA_DA_FILIACAO AS 'Data da Filiação' FROM Filiados_PTC
 WHERE DATA_DA_FILIACAO BETWEEN '02/01/2010 ' AND '01/03/2010'--11

 SELECT NOME_DO_FILIADO AS 'Nome do Filiado', DATA_DA_FILIACAO AS 'Data da Filiação' FROM Filiados_PTC
 WHERE DATA_DA_FILIACAO BETWEEN '12/09/2007' AND '31/12/2007'--12

 SELECT NOME_DO_FILIADO AS 'Nome do Filiado', SITUACAO_DO_REGISTRO AS 'Situação do Registro' FROM Filiados_PTC
 WHERE SITUACAO_DO_REGISTRO LIKE '%REGULAR%' --13

 SELECT NOME_DO_FILIADO AS 'Nome do Filiado', ZONA_ELEITORAL AS 'Zona Eleitoral' FROM Filiados_PTC
 WHERE ZONA_ELEITORAL LIKE '%203%'--14

 SELECT NOME_DO_FILIADO AS 'Nome do Filiado', ZONA_ELEITORAL AS 'Zona Eleitoral' FROM Filiados_PTC
 WHERE ZONA_ELEITORAL LIKE '%180%' --15

 SELECT NOME_DO_FILIADO AS 'Nome do Filiado', ZONA_ELEITORAL AS 'Zona Eleitoral' FROM Filiados_PTC
 WHERE ZONA_ELEITORAL LIKE '%199%'--16

 SELECT MAX (ZONA_ELEITORAL) AS 'Maior zona eleitoral' FROM Filiados_PTC --17

 SELECT MIN (ZONA_ELEITORAL) AS 'Menor zona eleitoral' FROM Filiados_PTC --18

 UPDATE Filiados_PTC SET SIGLA_DO_PARTIDO = 'PT'
 WHERE CODIGO_DO_MUNICIPIO = '36471' AND SIGLA_DO_PARTIDO = 'PTC'; --19

 --teste ex19
 SELECT * FROM Filiados_PTC
 WHERE CODIGO_DO_MUNICIPIO = '36471' AND SIGLA_DO_PARTIDO = 'PT'

 UPDATE Filiados_PTC SET SIGLA_DO_PARTIDO = 'PMDB'
 WHERE CODIGO_DO_MUNICIPIO = '38490' AND SIGLA_DO_PARTIDO = 'PTC'; --20

  --teste ex20
 SELECT * FROM Filiados_PTC
 WHERE CODIGO_DO_MUNICIPIO = '38490' AND SIGLA_DO_PARTIDO = 'PMDB'


 UPDATE Filiados_PTC SET SIGLA_DO_PARTIDO = 'PC'
 WHERE NOME_DO_MUNICIPIO LIKE 'SANTAN%' AND SIGLA_DO_PARTIDO = 'PTC'; --21

  --teste ex21-- DEU ERRO COMO O ESPERADO
 SELECT * FROM Filiados_PTC
 WHERE NOME_DO_MUNICIPIO LIKE 'SANTA%' AND SIGLA_DO_PARTIDO = 'PC'


 UPDATE Filiados_PTC SET SIGLA_DO_PARTIDO = 'PV', NOME_DO_PARTIDO = 'Partido Verde'
 WHERE NOME_DO_MUNICIPIO LIKE '%LIX' AND SIGLA_DO_PARTIDO = 'PTC';--22

 --teste ex22
 SELECT * FROM Filiados_PTC
 WHERE NOME_DO_MUNICIPIO LIKE '%LIX' AND SIGLA_DO_PARTIDO = 'PV'


 UPDATE Filiados_PTC SET SIGLA_DO_PARTIDO = 'PSDB', NOME_DO_PARTIDO = 'Partido da Social Democracia Brasileira'
 WHERE NOME_DO_MUNICIPIO LIKE '%ENCRUZILHADA%' AND SIGLA_DO_PARTIDO = 'PTC';--23

 --TESTE EX23
 SELECT * FROM Filiados_PTC
 WHERE NOME_DO_MUNICIPIO LIKE '%ENCRUZILHADA%' AND SIGLA_DO_PARTIDO = 'PSDB'


 UPDATE Filiados_PTC SET NOME_DO_FILIADO = 'JORGE LUIS MAGALHÃES DOS SANTOS'
 WHERE NOME_DO_FILIADO LIKE '%JORGE LUIS FERREIRA DOS SANTOS%' --24
 
 --TESTE EX24
 SELECT * FROM Filiados_PTC
 WHERE NOME_DO_FILIADO LIKE '%JORGE LUIS MAGALHÃES DOS SANTOS%'


 UPDATE Filiados_PTC SET NOME_DO_FILIADO = 'RENATA XAVIER RODRIGUES'
 WHERE NOME_DO_FILIADO LIKE '%BENTA XAVIER RODRIGUES%'--25

 --TESTE DO EX25
 SELECT * FROM Filiados_PTC
 WHERE NOME_DO_FILIADO LIKE '%RENATA XAVIER RODRIGUES%'


 UPDATE Filiados_PTC SET NOME_DO_FILIADO = 'NOEL LEITE DA SILVA'
 WHERE NOME_DO_FILIADO LIKE 'NOE LEITE DA SILVA'--26

 --TESTE DO EX26
 SELECT * FROM Filiados_PTC
 WHERE NOME_DO_FILIADO LIKE 'NOEL LEITE DA SILVA'


 UPDATE Filiados_PTC SET SITUACAO_DO_REGISTRO = 'REGULAR'
 WHERE NOME_DO_FILIADO = 'JOSIENE ANDRADE DE SOUZA'--27

 --TESTE DO EX27
 SELECT * FROM Filiados_PTC
 WHERE NOME_DO_FILIADO LIKE 'JOSIENE ANDRADE DE SOUZA'


 UPDATE Filiados_PTC SET SITUACAO_DO_REGISTRO = 'REGULAR'
 WHERE NOME_DO_FILIADO = 'ELIEL ALMEIDA SILVA'--28

 --TESTE DO EX28
 SELECT * FROM Filiados_PTC
 WHERE NOME_DO_FILIADO LIKE 'ELIEL ALMEIDA SILVA'


 UPDATE Filiados_PTC SET SITUACAO_DO_REGISTRO = 'DESFILIADO'
 WHERE NOME_DO_FILIADO LIKE 'ALINE DE SOUZA'--29

  --teste do ex29
 SELECT * FROM Filiados_PTC
 WHERE NOME_DO_FILIADO LIKE 'ALINE DE SOUZA'


 ALTER TABLE Filiados_PTC
 ADD SEXO CHAR(1) --30 (tive que pesquisar, pra fazer esse)

